### ISSUE TITLE
Can this be used to debug dynamic assemblies?

### ISSUE THREAD

**Issue by snakex64** [lordmilko/ClrDebug#16]
Hi!

I have been working on a visual programming environment that fully supports generating managed .NET .dlls.
I am still missing debugging capabilities such as visualizing the value of inputs/ouputs as well as being able to add breakpoints. 

Everything is generated in the new "PersistedAssemblyBuilder", I even made a couple changes to the upcoming .NET 10 version of it since it is still missing a lot of features.

Can this library be used for my needs ? I don't mind if I need to output more code when "compiling" in debug to allow debugging, such as emitting special events for each node or something.

Here's a shameless plug if you want to have a look, the second video shows the IL generation part:
[https://github.com/VisualNodeDev/NodeDev](https://github.com/VisualNodeDev/NodeDev)

**Comment by lordmilko** [comment]
This library provides managed wrappers around various Microsoft debugging/diagnostic APIs, including `ICorDebug`, which is the name commonly used to describe the .NET Unmanaged API. Using `ICorDebug`, you can develop your own debugger capable of debugging managed assemblies, just like other .NET debuggers such as Visual Studio and dnSpy.

Unless you are specifically interested in developing a debugger full of custom features not found elsewhere, I would advise simply using an existing debugger like dnSpy. dnSpy will show you any dynamic assemblies that exist in the process being debugged, and allow you to decompile, view locals and set breakpoints in these assemblies.

The only important thing to be aware of when debugging .NET assemblies using dnSpy is that, when you launch the target process outside of the debugger, the JIT will optimize executed methods as much as possible, which can make it hard to inspect locals and set breakpoints. For the best debugging experience, always launch the process you want to debug under the debugger, so that it can disable JIT optimization and allow a good debugging experience
